### PR TITLE
Add Vite and Tailwind set up

### PR DESCRIPTION
**Pull request by tomodwyer**
- Add a Node.js pipeline to the build process
- Install Vite and Tailwind
- Use Vite and Tailwind to build assets
- Add a [second app in django_vite](https://github.com/MrBin99/django-vite?tab=readme-ov-file#multi-app-configuration) to enable job-server assets to continue to exist alongside new assets

### CODE REVIEW

**Comment by tomodwyer** [comment]
On the environs package, I put in the Slack message but forgot to add here, happy for that to be removed! I just copied as much of the Job Server set up to get it working, but didn't know if I should mess with that to figure out how to get it working without the dependency.

---

As for the NPM step, if we don't do this (which is a totally valid option), I think we'll need to be very clear on how we do styling and JS.

Currently for styling in Airlock we have:

- [Tailwind styles from Job Server](https://github.com/opensafely-core/airlock/blob/a9d970f7e3d955461686e25055cbf1a33b045792/assets/dist/assets/base-AIgu2c3t.css)
- [Custom styles from Job Server](https://github.com/opensafely-core/airlock/blob/a9d970f7e3d955461686e25055cbf1a33b045792/assets/dist/assets/_datatable-BquxCQ6d.css)
- [Inline styles](https://github.com/opensafely-core/airlock/blob/a9d970f7e3d955461686e25055cbf1a33b045792/airlock/templates/_includes/header.html#L70)
- [Style blocks](https://github.com/opensafely-core/airlock/blob/a9d970f7e3d955461686e25055cbf1a33b045792/airlock/templates/file_browser/directory.html#L4-L20)
- [Custom stylesheets](https://github.com/opensafely-core/airlock/blob/a9d970f7e3d955461686e25055cbf1a33b045792/airlock/static/assets/components.css)
- [Using Tailwind styles that we hope are in the Job Server Tailwind CSS](https://github.com/opensafely-core/airlock/blob/a9d970f7e3d955461686e25055cbf1a33b045792/airlock/templates/add_files.html#L17)

And then for scripts we have:

- [Job Server scripts](https://github.com/opensafely-core/airlock/blob/a9d970f7e3d955461686e25055cbf1a33b045792/assets/dist/assets/_commonjsHelpers-BosuxZz1.js)
- [Third party vendor scripts copied in to the repo](https://github.com/opensafely-core/airlock/blob/a9d970f7e3d955461686e25055cbf1a33b045792/airlock/static/htmx-1.9.10.min.js)
- [Script blocks](https://github.com/opensafely-core/airlock/blob/a9d970f7e3d955461686e25055cbf1a33b045792/airlock/templates/file_browser/directory.html#L67-L81)
- [Linked JS files](https://github.com/opensafely-core/airlock/blob/a9d970f7e3d955461686e25055cbf1a33b045792/airlock/templates/login.html#L48-L50)
- [Airlock JS files which depend on Job Server scripts](https://github.com/opensafely-core/airlock/blob/a9d970f7e3d955461686e25055cbf1a33b045792/airlock/static/assets/datatable-loader.js)

Regardless of what decision we make, that will need to be cleaned up. It also stops us from migrating Airlock templates back in to Job Server, as you mentioned.

**Comment by bloodearnest** [comment]
Heya Tom, sorry for the delay

This looks sane to me, and as you say, is based on job-server.

We don't want the environs dep, thats for sure - are you happy to remove it?

Also, I feel like this may be missing some justfile integration, steps to setup npm and build the assets locally? Or is that to come later?

**Comment by evansd** [comment]
Happy to help on (or do) the environs stuff if that's easier, Thomas. No particular need for you to learn how Airlocks env var stuff works.

**Comment by tomodwyer** [comment]
> @tomodwyer Yep, happy to. Let me know when your branch is stable so I don't force-push over anything.

OK I've removed the "just groups" for the moment, so that should be the last of my changes. Over to you @evansd 🚀

**Comment by evansd** [comment]
@tomodwyer I thought this was all fairly straightforward but I seem to have broken `docker-test-dev` and I can't quite see why. I'll have to tackle this tomorrow when my brain is fresher.

**Comment by tomodwyer** [comment]
@evansd I think I've messed up the `just` commands in a small way. I'm going to add a commit on the end, but I don't think it will change the state of the docker-test-dev action.

**Review by evansd — APPROVED** [review]

**Pull request merged**
